Fix: getDebugInfo is not a function
The error `TypeError: getDebugInfo is not a function` is caused by the `AppSidebar` component trying to access a non-existent function from the `AuthContext`. The previous commit should have added this function, but it seems it was not correctly implemented. This commit will ensure that the `getDebugInfo` function is correctly implemented in the `AuthContext` and available to the `AppSidebar` component.